global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s


scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ "prometheus:9090" ]

  - job_name: api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'api:8091' ]

  - job_name: persons-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'persons-api:8092' ]

  - job_name: keycloak
    metrics_path: /metrics
    static_configs:
      - targets: [ 'keycloak:9000' ]

  - job_name: grafana
    metrics_path: /metrics
    static_configs:
      - targets: [ 'grafana:3000' ]

  - job_name: alloy
    metrics_path: /metrics
    static_configs:
      - targets: [ 'alloy:9080' ]

  - job_name: loki
    metrics_path: /metrics
    static_configs:
      - targets: [ 'loki:3100' ]

  - job_name: tempo
    metrics_path: /metrics
    static_configs:
      - targets: [ 'tempo:3200' ]

  - job_name: person-postgres
    static_configs:
      - targets: [ 'person-postgres-exporter:9187' ]

  - job_name: keycloak-postgres
    static_configs:
      - targets: [ 'keycloak-postgres-exporter:9187' ]