server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

ingester:
  trace_idle_period: 10s

compactor:
  compaction:
    compacted_block_retention: 48h

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces